#!/usr/bin/env python3
"""Regenerate index.md at the vault root from note frontmatter.

Also the shared home of the vault helpers (VAULT, iter_notes, parse_frontmatter,
note_title) imported by check_links.py and stale.py.
"""
from pathlib import Path

VAULT = Path(__file__).resolve().parent.parent
EXCLUDE_DIRS = {"repos", "sources", "export", "_templates", "tasks", "scripts", "private", ".venv", "facts", ".local-ankaios", ".local-autosd", ".git"}
TYPE_ORDER = ["event", "synthesis", "pattern", "playbook", "overview", "quickstart", "howto", "reference", "other"]


def iter_notes():
    """Yield every scanned .md file (Path), sorted by vault-relative path."""
    for path in sorted(VAULT.rglob("*.md")):
        rel = path.relative_to(VAULT)
        if rel.parts[0] in EXCLUDE_DIRS or rel.as_posix() == "index.md":
            continue
        yield path


def _scalar(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        value = value[1:-1]
    return value


def parse_frontmatter(text):
    """Return (meta dict, body). Supports flat scalars, [a, b] and block lists."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    meta, key = {}, None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return meta, "\n".join(lines[i + 1:])
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("- ") or stripped == "-":
            if key is not None:
                if not isinstance(meta.get(key), list):
                    meta[key] = []
                meta[key].append(_scalar(stripped[1:]))
            continue
        if ":" in line:
            key, value = line.split(":", 1)
            key, value = key.strip(), value.strip()
            if value.startswith("[") and value.endswith("]"):
                meta[key] = [_scalar(v) for v in value[1:-1].split(",") if v.strip()]
            else:
                meta[key] = _scalar(value)
    return {}, text  # unterminated frontmatter: treat as none


def note_title(meta, body, path):
    if meta.get("title"):
        return meta["title"]
    for line in body.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def load_note(path):
    meta, body = parse_frontmatter(path.read_text(encoding="utf-8"))
    return meta, note_title(meta, body, path)


def _component(meta):
    return f"cluster:{meta['cluster']}" if meta.get("cluster") else _cell(meta.get("component"))


def _cell(value):
    if isinstance(value, list):
        value = ", ".join(value)
    return str(value or "").replace("|", "\\|")


def build():
    rows = []
    for path in iter_notes():
        meta, title = load_note(path)
        ntype = meta.get("type") if meta.get("type") in TYPE_ORDER else "other"
        rows.append((ntype, path.relative_to(VAULT).as_posix(), title, meta))

    statuses = {}
    for _, _, _, meta in rows:
        s = _cell(meta.get("status")) or "none"
        statuses[s] = statuses.get(s, 0) + 1
    summary = ", ".join(f"{k}: {v}" for k, v in sorted(statuses.items()))

    out = ["# Index", "", "<!-- Generated by scripts/build_index.py. Do not edit by hand. -->", "",
           f"**{len(rows)} notes** ({summary or 'none'})", ""]
    for ntype in TYPE_ORDER:
        group = [r for r in rows if r[0] == ntype]
        if not group:
            continue
        group.sort(key=lambda r: (_component(r[3]).lower(), r[2].lower(), r[1]))
        out += [f"## {ntype} ({len(group)})", "",
                "| Title | Component | Status | Last-verified | Tags |",
                "|---|---|---|---|---|"]
        for _, rel, title, meta in group:
            link = f"[{_cell(title)}]({rel.replace(' ', '%20')})"
            out.append(f"| {link} | {_component(meta)} | {_cell(meta.get('status'))} "
                       f"| {_cell(meta.get('last-verified'))} | {_cell(meta.get('tags'))} |")
        out.append("")
    (VAULT / "index.md").write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {VAULT / 'index.md'}: {len(rows)} notes")


if __name__ == "__main__":
    build()
